### ISSUE TITLE
The helm chart on artifacthub contain old api

### ISSUE THREAD

**Issue by yodatak** [gissilabs/charts#51] opened 2024-03-20 10:45 UTC
The helm chart present on artifact hub is old and contain deprecated  ingress api but the git is good but not the helm chart published in artifacthub

```yaml
{{- if semverCompare">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
```

https://artifacthub.io/packages/helm/gissilabs/leantime?modal=template&template=ingress.yaml

The chart is not realy updated in version leantime-1.1.0.tgz
https://github.com/gissilabs/charts/actions/runs/8193895940/artifacts/1307134620

**Comment by sgissi** [comment] 2024-04-27 21:37
@yodatak Can you check if it is better now? I released a new chart today.

**Comment by yodatak** [comment] 2024-05-08 15:26
Its now fixed but it don't work because pathType is mandatory see  my pR ( untested  for now) #54

**Comment by sgissi** [comment] 2024-05-10 14:59
Hi, I merged the PR. Also, beyond pathType, the backend service changed from serviceName/servicePort to service.name and service.port.number/service.port.name. I created a new version of the chart (1.2.0), can you test please?

**Comment by sgissi** [comment] 2024-05-17 17:56
Closing the issue for now as the latest charts should work as intended. Please re-open if not the case.

**Closed by sgissi** 2024-05-17 17:56 UTC
